plugins {
    id 'com.android.application'
}

android {
    namespace 'com.dailykitchenpub.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.dailykitchenpub.app'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
